Add Maintainer and Governance Info
tern-tools/tern pull request #1037
Opened 2021-09-22 19:16 UTC by rnjudge

It's important for open source projects to have clear guidelines and
expectations around governance and maintainership.

Resolves #990

Signed-off-by: Rose Judge <rjudge@vmware.com>

2021-09-22 19:29 UTC, rnjudge commented
@geekygirldawn could you review when you have a moment? :)

2021-09-22 19:35 UTC, nishakm requested changes
As a small project with only 2 maintainers, I don't think a supermajority vote is possible. I would suggest going with lazy consensus on decisions for now.

2021-09-22 19:35 UTC, nishakm commented on GOVERNANCE.md
> +A supermajority is defined as two-thirds of members in the group.
There are currently only two maintainers. How can we get to a supermajority without a third one?

2021-09-23 12:06 UTC, geekygirldawn commented
> As a small project with only 2 maintainers, I don't think a supermajority vote is possible. I would suggest going with lazy consensus on decisions for now.

I agree with the point about a supermajority for now. 

I would leave the **project** decision-making as lazy consensus, but for new maintainers, governance changes, and removing maintainers, I would remove the lazy and require consensus between the 2 of you until we have additional maintainers. People get busy, distracted, and miss things, so I prefer not to have lazy consensus for big decisions. 

Does this seem reasonable?

Otherwise, it looks great, and thank you so much for doing this!

2021-09-23 12:57 UTC, nishakm commented
> I would leave the **project** decision-making as lazy consensus, but for new maintainers, governance changes, and removing maintainers, I would remove the lazy and require consensus between the 2 of you until we have additional maintainers. People get busy, distracted, and miss things, so I prefer not to have lazy consensus for big decisions.

+1 on this. Thanks for reviewing @geekygirldawn!

2021-09-23 20:43 UTC, rnjudge commented
@geekygirldawn @nishakm changed the "Lazy Consensus" section to be:

```
To maintain velocity in the Tern project, the concept of [Lazy Consensus](http://en.osswiki.info/concepts/lazy_consensus) is practiced. Lazy Consensus is practiced for all projects and decisions in the `tern-tools` org.

Lazy consensus does _not_ apply to the process of:
* Removal of maintainers from Tern
* Governance changes
* Adding new maintainers to Tern

For the above mentioned processes, consensus between @rnjudge and @nishakm is required until there are enough maintainers for a supermajority vote.
```

2021-09-23 22:10 UTC, nishakm approved these changes

2021-09-23 22:10 UTC, merged