Fix CycloneDX report generation
tern-tools/tern pull request #1102
Opened 2022-01-14 21:37 UTC by rnjudge

Commit 0891287 introduced using the OCIImage class instead of
DockerImage for container image analysis. There is a difference in the
name and type of the variable that holds the repository tag ('repotags'
list for DockerImage vs 'repotag' string for OCIImage) which is causing
the CycloneDX format to break. This was not caught prior to the release
because there are no tests for the CycloneDX format in the ci test file.

This commit resolves the CycloneDX format bug by using the repository
tag variable name depending on image type and also adds an appropriate
test in the ci test file to try to avoid this issue in the future.

Lastly, we add 'undefined-variable' to the list of pylint and pyflakes
warnings to ignore as it was being incorrectly surfaced during
prospector runs.

Resolves #1097

Signed-off-by: Rose Judge <rjudge@vmware.com>

2022-01-19 18:03 UTC, nishakm requested changes
Just one small request to put the # disable undefined variable check just for the change. I think we can think about turning it off globally when more instances of the check show up.

2022-01-20 04:36 UTC, rnjudge commented on .prospector.yaml
> +    - F821  # undefined variable
Hmm, `# noqa: F821 ` at the end of line 33 and line 36 doesn't seem to indicate to prospector to ignore or supress the error. Any tips?

2022-01-20 04:53 UTC, rnjudge commented on .prospector.yaml
> +    - F821  # undefined variable
I've additionally tried just `# noqa` and `# NOQA` to try to supress pyflakes errors to no avail. I'm also going a bit mad trying to suppress the pylint errors on a per-line basis. Prospector gives me the pylint error that I am trying to suppress then tells me its useless to try to suppress that error? 


```
build/lib/tern/formats/cyclonedx/cyclonedxjson/image_helpers.py
  Line: 31
    pylint: undefined-variable / Undefined variable 'DockerImage' (col 29)
  Line: 34
    pylint: undefined-variable / Undefined variable 'OCIImage' (col 31)

tern/formats/cyclonedx/cyclonedxjson/image_helpers.py
  Line: 33
    pylint: useless-suppression / Useless suppression of 'undefined-variable'
  Line: 36
    pylint: useless-suppression / Useless suppression of 'undefined-variable'

```

2022-01-20 18:09 UTC, nishakm approved these changes

2022-01-20 18:09 UTC, merged