Add instructions for Kubernetes Job
tern-tools/tern pull request #1114
Opened 2022-02-03 14:54 UTC by nishakm

This commit adds instructions to deploy Tern as a Kubernetes Job.

Fixes #1111

Signed-off-by: Nisha K <nishak@vmware.com>

2022-02-10 15:42 UTC, nishakm commented
@rnjudge you mentioned you had left a review, but I don't see any. Can you review please?

2022-02-10 19:18 UTC, rnjudge requested changes

2022-02-11 17:12 UTC, nishakm commented on README.md
> +$ minikube image build -t tern:2.9.1 -f Dockerfile .
Maybe `tern:test`? For minikube image, you require a tag.

2022-02-11 17:19 UTC, rnjudge commented on README.md
> +$ minikube image build -t tern:2.9.1 -f Dockerfile .
`tern:test` works for me. I'm not against a tag, just wanted to make it generic so the docs hold up long after release 2.9.1 :D

2022-02-11 23:16 UTC, rnjudge commented on README.md
> +## Creating a Kubernetes Job<a name="k8s-deployment">
Ack, sorry I didn't catch this before :( `<a name="k8s-deployment">` should be `<a name="k8s-job"> to be consistent with how you defined it above.. (line 22)

2022-02-15 02:30 UTC, rnjudge approved these changes

2022-02-15 02:30 UTC, merged