Added run_extension for an ImageLayer object
tern-tools/tern pull request #876
Opened 2021-02-09 09:48 UTC by m1-key

I have added a function execute_layer in executor.py
of extensions folder and also in cve_bin_tool/executor.py
and in scancode/executor.py

Solves Issue: #857
Work towards: #850

Signed-off-by: m1key <shubhamtiwari.tiwari84@gmail.com>

2021-02-11 23:52 UTC, nishakm requested changes
Looks good to me except for one change required to make this work

2021-02-11 23:52 UTC, nishakm commented on tern/analyze/passthrough.py
> +        return mgr.driver.execute(image_layer, redo)
This should be `execute_layer` -> the new functions you have added to the extensions.

2021-02-11 23:52 UTC, nishakm commented on tern/extensions/cve_bin_tool/executor.py
> +        print(image_layer.analyzed_output)
Good!

2021-02-12 06:48 UTC, m1-key commented
@nishakm Sorry, I accidently closed the PR. I have opened another PR #880 . Sorry for the inconvenience.

2021-02-12 09:01 UTC, m1-key commented on tern/extensions/cve_bin_tool/executor.py
> +        print(image_layer.analyzed_output)
> Good!

Thanks :)

2021-02-12 16:48 UTC, nishakm approved these changes

2021-02-12 16:49 UTC, nishakm commented
Looks good. Merging

2021-02-12 16:49 UTC, merged